esphome:
  name: bell
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wlan
  password: !secret wlan_pass

# Enable logging
logger:
  level: DEBUG

web_server:
  port: 80
  auth:
    username: !secret webserver_name
    password: !secret webserver_pass

# Enable Home Assistant API
#api:

ota:

# connect to ioBroker
mqtt:
  broker: 192.168.178.100
  username: !secret mqtt_name
  password: !secret mqtt_pass

# control LED strip
sensor:
  - platform: adc
    pin: A0
    name: "Input 1"
    update_interval: 0.1s
