esphome:
  name: cart
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wlan_felix
  password: !secret wlan_felix_pass
  power_save_mode: high
  ap:
    ssid: "Fallback Hotspot"
    password: !secret fallback_pass

captive_portal:

# Enable logging
logger:
  level: DEBUG

web_server:
  port: 80
  auth:
    username: !secret webserver_name
    password: !secret webserver_pass

ota:

# connect to ioBroker
mqtt:
  broker: 192.168.0.143
  username: !secret mqtt_name
  password: !secret mqtt_pass

# Button IN on D3-D4
binary_sensor:
  - platform: gpio
    pin:
      number: D1
      inverted: True
      mode: INPUT
    id: button1
    on_press:
      then:
        - switch.turn_on: switch1
    on_release:
      then:
        - switch.turn_off: switch1
  - platform: gpio
    pin:
      number: D4
      inverted: True
      mode: INPUT
    id: button2
    on_press:
      then:
        - switch.turn_on: switch2
    on_release:
      then:
        - switch.turn_off: switch2

switch:
  - platform: gpio
    pin: D3
    id: switch1
    #    interlock: &interlock_group [switch1, switch2]
    on_turn_on:
      then:
        - light.turn_on:
            id: maxbrightness
            red: 100%
            green: 100%
            blue: 100%
    on_turn_off:
      then:
        - light.turn_off:
            id: maxbrightness
  - platform: gpio
    pin: D2
    id: switch2
    #   interlock: *interlock_group
    on_turn_on:
      - light.turn_on: car
    on_turn_off:
      - light.turn_off: car

# control LED strip
# LED out on D7-8
light:
  - platform: fastled_clockless
    chipset: WS2812
    pin: D7
    num_leds: 100
    rgb_order: GRB
    name: "Maximum Brightness"
    id: maxbrightness
    restore_mode: ALWAYS_OFF
  - platform: fastled_clockless
    chipset: WS2812
    pin: D8
    num_leds: 200
    rgb_order: GRB
    name: "Car Mode"
    id: car
    restore_mode: ALWAYS_OFF
