esphome:
  name: cart
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wlan
  password: !secret wlan_pass
  power_save_mode: high
  ap:
    ssid: "Fallback Hotspot"
    password: !secret fallback_pass

# Enable logging
logger:
  level: DEBUG

web_server:
  port: 80
  auth:
    username: !secret webserver_name
    password: !secret webserver_pass

ota:

# connect to ioBroker
mqtt:
  broker: 192.168.178.100
  username: !secret mqtt_name
  password: !secret mqtt_pass

# Button IN on D5-D6
binary_sensor:
  - platform: gpio
    pin:
      number: D5
      inverted: True
    id: button1
    on_press:
      then:
        - switch.turn_on: switch1
    on_release:
      then:
        - switch.turn_off: switch1
  - platform: gpio
    pin:
      number: D6
      inverted: True
    id: button2
    on_press:
      then:
        - switch.turn_on: switch2
    on_release:
      then:
        - switch.turn_off: switch2

switch:
  - platform: gpio
    pin: D3
    id: switch1
    interlock: &interlock_group [switch1, switch2]
    on_turn_on:
      - light.addressable_set:
          id: maxbrightness
          range_from: 0
          range_to: 50
          red: 100%
          green: 0%
          blue: 0%
      - light.addressable_set:
          id: maxbrightness
          range_from: 51
          range_to: 100
          red: 0%
          green: 100%
          blue: 0%
    on_turn_off:
      - light.addressable_set:
          id: maxbrightness
          range_from: 0
          range_to: 100
          red: 10%
          green: 10%
          blue: 10%
  - platform: gpio
    pin: D4
    id: switch2
    interlock: *interlock_group
    on_turn_on:
      - light.addressable_set:
          id: car
          range_from: 0
          range_to: 50
          red: 50%
          green: 0%
          blue: 50%
      - light.addressable_set:
          id: car
          range_from: 51
          range_to: 100
          red: 0%
          green: 50%
          blue: 50%
    on_turn_off:
      - light.addressable_set:
          id: car
          range_from: 0
          range_to: 100
          red: 10%
          green: 10%
          blue: 10%

# control LED strip
# LED out on D1-2
light:
  - platform: fastled_clockless
    chipset: WS2811
    pin: D6
    num_leds: 100
    rgb_order: GRB
    name: "Maximum Brightness"
    id: maxbrightness
    restore_mode: ALWAYS_OFF
  - platform: fastled_clockless
    chipset: WS2811
    pin: D7
    num_leds: 100
    rgb_order: GRB
    name: "Car Mode"
    id: car
    restore_mode: ALWAYS_OFF
