esphome:
  name: "kitchen2"
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wlan
  password: !secret wlan_pass

captive_portal: 

# Enable logging
logger:
  level: DEBUG

web_server:
  port: 80
  auth:
    username: !secret webserver_name
    password: !secret webserver_pass

# Enable Home Assistant API
api:

ota:

# connect to ioBroker
mqtt:
  broker: !secret broker
  username: !secret mqtt_name
  password: !secret mqtt_pass
  on_message:
    - topic: kitchen/light/arbeitsflaeche/node
      payload: "true"
      then:
        - light.turn_on: "arbeitsflaeche"
    - topic: kitchen/light/arbeitsflaeche/node
      payload: "false"
      then:
        - light.turn_off: "arbeitsflaeche"


# control LED strip
light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D7
    num_leds: 100
    rgb_order: GRB
    name: "Arbeitsflaeche"
    id: arbeitsflaeche
    default_transition_length: 0s
